# Generated by Django 2.1.7 on 2019-04-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryID', models.CharField(max_length=255, unique=True)),
                ('insertionDate', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('zipcode', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('sales_price', models.DecimalField(decimal_places=5, default=None, max_digits=20)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('homeid', models.CharField(max_length=255)),
                ('FG_PCT_RANK', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BasicStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DefenseStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryID', models.CharField(max_length=255, unique=True)),
                ('insertionDate', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HustleStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryID', models.CharField(max_length=255, unique=True)),
                ('insertionDate', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('OFF_LOOSE_BALLS_RECOVERED', models.CharField(max_length=255, unique=True)),
                ('CONTESTED_SHOTS', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RosterStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
