# Generated by Django 2.1.7 on 2019-04-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaleurculture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatesModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='advancedstats',
            name='address',
        ),
        migrations.RemoveField(
            model_name='advancedstats',
            name='city',
        ),
        migrations.RemoveField(
            model_name='advancedstats',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='advancedstats',
            name='entryID',
        ),
        migrations.RemoveField(
            model_name='advancedstats',
            name='homeid',
        ),
        migrations.RemoveField(
            model_name='advancedstats',
            name='insertionDate',
        ),
        migrations.RemoveField(
            model_name='advancedstats',
            name='sales_price',
        ),
        migrations.RemoveField(
            model_name='advancedstats',
            name='state',
        ),
        migrations.RemoveField(
            model_name='advancedstats',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='defensestats',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='defensestats',
            name='entryID',
        ),
        migrations.RemoveField(
            model_name='defensestats',
            name='insertionDate',
        ),
    ]
