# Generated by Django 2.1.7 on 2019-04-14 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chaleurculture', '0002_auto_20190413_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedstats',
            name='AST_PCT',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='AST_PCT_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='AST_RATIO',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='AST_RATIO_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='AST_TO',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='AST_TO_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='DEF_RATING',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='DEF_RATING_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='DREB_PCT',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='DREB_PCT_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='EFG_PCT',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='EFG_PCT_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='FGA',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='FGA_PG',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='FGA_PG_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='FGA_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='FGM',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='FGM_PG',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='FGM_PG_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='FGM_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='FG_PCT',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='GP',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='GP_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='L',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='L_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='MIN',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='MIN_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='NET_RATING',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='NET_RATING_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='OFF_RATING',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='OFF_RATING_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='OREB_PCT',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='OREB_PCT_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='PACE',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='PACE_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='PIE',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='PIE_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='PLAYER_ID',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='PLAYER_NAME',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='REB_PCT',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='REB_PCT_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='TEAM_ABBREVIATION',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='TEAM_ID',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='TM_TOV_PCT_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='TS_PCT',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='TS_PCT_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='USG_PCT',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='USG_PCT_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='W',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='W_PCT',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='W_PCT_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='W_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='eDEF_RATING',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='eDEF_RATING_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='eNET_RATING',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='eNET_RATING_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='eOFF_RATING',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='eOFF_RATING_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='ePACE',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='ePACE_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='entryID',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='insertionDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='sp_work_DEF_RATING',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='sp_work_DEF_RATING_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='sp_work_NET_RATING',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='sp_work_NET_RATING_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='sp_work_OFF_RATING',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='sp_work_OFF_RATING_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='sp_work_PACE',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='sp_work_PACE_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='advancedstats',
            name='FG_PCT_RANK',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
