# Generated by Django 2.1.7 on 2019-04-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaleurculture', '0003_auto_20190414_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedstats',
            name='TM_TOV_PCT',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
