# Generated by Django 2.1.7 on 2019-04-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaleurculture', '0004_advancedstats_tm_tov_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedstats',
            name='CFID',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
