# Generated by Django 2.1.7 on 2019-04-14 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaleurculture', '0005_advancedstats_cfid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedstats',
            name='TEAM_ABBREVIATION',
        ),
    ]
