# Generated by Django 2.1.7 on 2019-04-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaleurculture', '0006_remove_advancedstats_team_abbreviation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvancedStats',
            new_name='Advanced_Stats',
        ),
    ]
