# Generated by Django 2.1.7 on 2019-04-14 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaleurculture', '0008_auto_20190414_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedstats',
            name='entryID',
        ),
    ]
