# Generated by Django 2.1.7 on 2019-04-15 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chaleurculture', '0010_auto_20190415_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hustlestats',
            name='entryID',
        ),
        migrations.AddField(
            model_name='defensestats',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='defensestats',
            name='insertionDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='AGE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='CHARGES_DRAWN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='CONTESTED_SHOTS_2PT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='CONTESTED_SHOTS_3PT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='DEFLECTIONS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='DEF_LOOSE_BALLS_RECOVERED',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='G',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='LOOSE_BALLS_RECOVERED',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='MIN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='PCT_LOOSE_BALLS_RECOVERED_DEF',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='PCT_LOOSE_BALLS_RECOVERED_OFF',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='PLAYER_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='PLAYER_NAME',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='SCREEN_ASSISTS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='SCREEN_AST_PTS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hustlestats',
            name='TEAM_ABBREVIATION',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='AGE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='BIRTH_DATE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='EXP',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='HEIGHT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='LeagueID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='NUM',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='PLAYER',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='PLAYER_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='POSITION',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='SCHOOL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='SEASON',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='TeamID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rosterstats',
            name='insertionDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updatesmodels',
            name='AdvancedStatsStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='updatesmodels',
            name='DefenseStatsStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='updatesmodels',
            name='HustleStatsStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='updatesmodels',
            name='RegStatsStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='updatesmodels',
            name='RosterStatsStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='updatesmodels',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='updatesmodels',
            name='insertionDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hustlestats',
            name='CONTESTED_SHOTS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hustlestats',
            name='OFF_LOOSE_BALLS_RECOVERED',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
