# Generated by Django 2.1.7 on 2019-04-15 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chaleurculture', '0011_auto_20190415_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicstats',
            name='AGE',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='AST',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='AST_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='BLK',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='BLKA',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='BLKA_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='BLK_RANK',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='DD2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='DD2_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='DREB',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='DREB_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FG3A',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FG3A_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FG3M',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FG3M_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FG3_PCT',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FG3_PCT_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FGA',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FGA_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FGM',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FGM_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FG_PCT',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FG_PCT_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FTA',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FTA_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FTM',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FTM_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FT_PCT',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='FT_PCT_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='GP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='GP_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='L',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='L_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='MIN',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='MIN_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='NBA_FANTASY_PTS',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='NBA_FANTASY_PTS_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='OREB',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='PF',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='PFD',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='PFD_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='PF_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='PLAYER_ID',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicstats',
            name='PLUS_MINUS',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='PLUS_MINUS_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='PTS',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='PTS_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='REB',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='REB_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='STL',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='STL_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='TD3',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='TD3_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='TEAM_ID',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicstats',
            name='TOV',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='TOV_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='W',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='W_PCT',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='W_PCT_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='W_RANK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='insertionDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
