# Generated by Django 2.1.7 on 2019-04-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaleurculture', '0015_rosterstats_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterstats',
            name='PCTDIFFWEIGHT',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20),
        ),
    ]
