# Generated by Django 2.1.7 on 2019-04-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaleurculture', '0016_rosterstats_pctdiffweight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdatesModels',
            new_name='UpdatesStats',
        ),
    ]
