# Generated by Django 2.1.7 on 2019-03-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USAHOMESaleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryID', models.CharField(max_length=255, unique=True)),
                ('insertionDate', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('zipcode', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('sales_price', models.DecimalField(decimal_places=5, default=None, max_digits=20)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('homeid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='USAHomesRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryID', models.CharField(max_length=255, unique=True)),
                ('insertionDate', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('zipcode', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('homeid', models.CharField(max_length=255)),
            ],
        ),
    ]
