# Generated by Django 2.1.7 on 2019-05-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zillna', '0002_usahomespricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usahomesrawdata',
            name='emaildate',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usahomesrawdata',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
