# Generated by Django 2.1.7 on 2019-05-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zillna', '0003_auto_20190508_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usahomesrawdata',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
