# Generated by Django 2.1.7 on 2019-05-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zillna', '0004_auto_20190508_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usahomesaleinfo',
            name='homeid',
        ),
        migrations.AddField(
            model_name='usahomesaleinfo',
            name='bathrooms',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='usahomesaleinfo',
            name='bedrooms',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='usahomesaleinfo',
            name='latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usahomesaleinfo',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usahomesaleinfo',
            name='sales_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usahomesaleinfo',
            name='tax_assessment',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='usahomesaleinfo',
            name='tax_assessment_year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usahomesaleinfo',
            name='usecode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usahomesaleinfo',
            name='year_built',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
