# Generated by Django 2.1.7 on 2019-05-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zillna', '0005_auto_20190508_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usahomesaleinfo',
            name='entryID',
        ),
    ]
